config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/about'
  root to:'home#top'
  resources :users, only: [:show, :index, :edit, :update]
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

     belongs_to :user
     has_many :book_comments, dependent: :destroy
     has_many :favorites, dependent: :destroy

     def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
     end


    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
   belongs_to :user
   belongs_to :book

   validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

    def after_sign_in_path_for(resource)
        user_path(resource)
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book), notice: 'You have creatad book successfully.'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end


  def show
    @book = Book.new
    @showbook = Book.find(params[:id])
    @user = @showbook.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def edit
    @user = current_user
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

 private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    #redirect_to books_path
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
    #redirect_to books_pathS
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body">
    <div class="container">
        <%=  notice %>
        <div class="row">
	        <div class="col-md-6 col-md-offset-3">
		        <h1>Editing Book</h1>
		            <% if @book.errors.any? %>
                        <ul class="red">
                            <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
                                <% @book.errors.full_messages.each do |message| %>
                                    <li><%= message%></li>
                                <% end %>
                        </ul>
                    <% end %>

		            <%= form_with model: @book, local:true do |f| %>
                        <div class="field row">
                            <label for="book_title">Title</label>
                            <%= f.text_field :title, class:"col-xs-12 book_title" %>
                        </div>

                        <div class="field row">
                            <label for="book_opinion">Opinion</label>
                            <%= f.text_area :body, class:"col-xs-12 book_body" %>
                        </div>
                        <br>
                        <div class="actions row">
                            <%= f.submit 'Update Book',class:"btn btn-primary col-xs-12" %>
                        </div>
                    <% end %>

		        <%= link_to "Show", book_path(@book) %>|
		        <%= link_to "Back", books_path %>
            </div>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="body">
    <div class="container">
    <%=  notice %>
            <% if @book.errors.any? %>
                <ul class="red">
                  <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message%></li>
                  <% end %>
                </ul>
            <% end %>

            <div class="row">

                <%= render 'shared/side', user: @user, book: @book %>

                <div class="col-xs-9">
                    <h2>Books</h2>
                        <table class="table table-hover table-inverse">
                            <thead>
                                <th></th>
                                <th>Title</th>
                                <th>Opinion</th>
                                <th colspan="3"></th>
                            </thead>

                            <% @books.each do |book| %>
                            <tbody>
                                <th>
                                    <%= link_to user_path(book.user) do %>
                                        <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no2_image.jpg"%>
                                    <% end %>
                                </th>
                                <th><%= link_to book_path(book) do %><%= book.title %><% end %></th>
                                <th><%= book.body %></th>
                                <% if book.favorited_by?(current_user) %>
                                    <th>
                                        <%= link_to book_favorites_path(book.id), method: :delete do %>
                                            <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
                                            <%= book.favorites.count %> いいね
                                        <% end %>
                                    </th>
                                <% else %>
                                    <th>
                                        <%= link_to book_favorites_path(book), method: :post do %>
                                            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                                            <%= book.favorites.count %> いいね
                                        <% end %>
                                    </th>
                                <% end %>
                                <th>コメント数:<%= book.book_comment_ids.count %></th>
                            <% end %>
                            </tbody>
                        </table>
                </div>
            </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="body">
    <div class="container">
    <p class="gr-index"><%=  notice %></p>
        <div class="row">

            <%= render 'shared/side', user: @user, book: @book %>

            <div class="col-xs-9">
		        <h2>Book detail</h2>
		        <table class="table">
		            <tbody>
                        <td><%= link_to user_path(@showbook.user) do %>
                            <%= attachment_image_tag @showbook.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"%>
                            <br><%= @showbook.user.name %><% end %>
                        </td>
                        <td><%= link_to book_path(@showbook) do %><%= @showbook.title %><% end %></td>
                        <td><%= @showbook.body %></td>
                        <% if @showbook.favorited_by?(current_user) %>
                            <th>
                                <%= link_to book_favorites_path(@showbook.id), method: :delete do %>
                                    <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
                                    <%= @showbook.favorites.count %> いいね
                                <% end %>
                            </th>
                        <% else %>
                            <th>
                                <%= link_to book_favorites_path(@showbook), method: :post do %>
                                    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                                    <%= @showbook.favorites.count %> いいね
                                <% end %>
                            </th>
                        <% end %>

                        <% if @showbook.user == current_user %>
                            <td><%= link_to edit_book_path(@showbook) do %><span class="btn-sm btn-success edit_book">Edit</span><% end %></td>
                            <td><%= link_to "Destroy", book_path(@showbook), method: :delete, class:"btn-sm btn-danger destroy_book", "data-confirm" => "本当に消しますか？" %></td>
                        <% else %>
                            <td></td>
                            <td></td>
                        <% end %>
                    </tbody>
                </table>

                <table>
                    <% @showbook.book_comments.each do |book_comment| %>
                        <tbody>
                            <td><%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no2_image.jpg"%></td>
                            <td><%= book_comment.comment %></td>
                            <td>
                                <% if book_comment.user == current_user %>
                                    <td><%= link_to "Destroy",  book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn-sm btn-danger destroy_book"%></td>
                                <% end %>
                            </td>
                        </tbody>
                    <% end %>
                </table>
                <br>

                <%= form_with(model:[@showbook, @book_comment], local: true) do |f| %>
                    <%= f.text_area :comment, rows:'5', class: "form-control"%>
                    <%= f.submit "送信", class: "pull-right" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/home/about.html.erb
<div class="body">
<div class="container">
    <p id="notice"></p>
    <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
</div>
</div>

app/views/home/top.html.erb
<div class="body">
      <div class="container">
        <p class="gr-index"><%=  notice %></p>
        <div class="row">
          <div class="top-message col-md-offset-3 col-md-6">
            <h1><font _mstmutation="1">welcome to </font><span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
              <p><font _mstmutation="1">In  <strong _mstmutation="1">Bookers</strong>, </font><span class="glyphicon glyphicon-book"></span></p>
              <p>you can share and exchange  your opinions , inpressions , and emotions</p>
              <p> about various books!</p>

            <div class="btn-wrapper">
              <div class="row">
                 <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
              </div>
              <div class="row">
                <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
              </div>
              <br>
            </div>
            </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span class="header-bookers">Bookers</span>
    </nav>
     <% if user_signed_in? %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to user_path(current_user.id) do %>
            <div class="glyphicon glyphicon-home home"> Home</div><% end %></li>
          <li><%= link_to users_path do %>
          <div class="glyphicon glyphicon-user users"> Users</div><% end %></li>
          <li><%= link_to books_path do %>
            <div class="glyphicon glyphicon-book books"> Books</div><% end %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
              <div class="glyphicon glyphicon-log-out logout"> logout</div><% end %></li>
      </ul>
    </nav>
    <% else %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
          <li><%= link_to home_about_path do %>
            <div class="glyphicon glyphicon-link about"> About</div><% end %></li>
          <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a></li>
          <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a></li>
      </ul>
      </ul>
    </nav>
    <% end %>
  </div>
</header>
  <body>
    <%= yield %>
  </body>
  <footer>
    <div class="container">
  	  <div class="row">
    	  <div class="col-xs-3 col-xs-offset-9">
    		  <p>CopyRight Infratop.inc</p>
    	  </div>
      </div>
    </div>
  </footer>
</html>

app/views/shared/_side.html.erb
<div class="col-xs-3">
    <h2>User info</h2>
    <table class="table">
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"%>
            <tbody>
                <tr></tr>
                <tr>
    	            <th>name</th>
    	            <th><%= user.name %></th>
    	        </tr>

    	        <tr>
    	            <th>introduction</th>
    	            <th><%= user.introduction %></th>
    	        </tr>
    	    </tbody>
    </table>

    <div class="row">
        <% if user == current_user %>
            <%= link_to edit_user_path(user) do %>
                <div class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></div>
            <% end %>

        <% else %>
            <%= link_to user_path(current_user) do %>
                <div class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></div>
            <% end %>
        <% end %>
    </div>

    <h2>New book</h2>
    <%= form_with model: book, local:true do |f| %>
        <div class="field row">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"col-xs-12 book_title" %>
        </div>

        <div class="field row">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"col-xs-12 book_body" %>
        </div>
        <br>
        <div class="actions row">
            <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="body">
    <div class="container">
    <h2>User info</h2>
      <% if @user.errors.any? %>
        <ul class="red">
          <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message%></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @user, local:true do |f| %>
        <div class="field">
          <label for="user_name">Name</label>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "ファイルの選択" %>
        </div>

        <div class="field">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction %>
        </div>

        <div class="actions">
          <%= f.submit 'Update User' %>
        </div>
      <% end %>
      </div>
</div>

app/views/users/index.html.erb
<div class="body">
    <div class="container">
        <%=  notice %>
        <div class="row">

            <%= render 'shared/side', user: @user, book: @book %>

            <div class="col-xs-9">
                <h2>Users</h2>
                <table class="table">
                    <thead>
                        <th>image</th>
                        <th>name</th>
                        <th colspan="1"></th>
                    </thead>

                    <% @users.each do |user| %>
                    <tbody>
                        <th><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no2_image.jpg"%></th>
                        <th><%= user.name %></th>
                        <th><%= link_to "Show", user_path(user) %></th>
                    </tbody>
                    <% end %>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="body">
    <div class="container">
        <p class="gr-index"><%=  notice %></p>
        <div class="row">

            <%= render 'shared/side', user: @user, book: @book %>

            <div class="col-xs-9">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="3"></th>
                    </thead>

                    <% @books.each do |book| %>
                    <tbody>
                        <th><%= link_to user_path(book.user) do %><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no2_image.jpg"%><% end %></th>
                        <th><%= link_to book_path(book) do %><%= book.title %><% end %></th>
                        <th><%= book.body %></th>
                    </tbody>
                    <% end %>
                </table>
            </div>
        </div>
    </div>
</div>